// Picks only the font chunks whose unicode-range covers characters used on the site,
// copies them to assets/fonts and writes assets/fonts.css.
// Usage: node tools/build-fonts.mjs <dir containing extracted @fontsource packages>
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const src = process.argv[2];
if (!src) { console.error('usage: node tools/build-fonts.mjs <fontsource dir>'); process.exit(1); }

const FACES = [
  { pkg: 'noto-serif-tc', files: ['300.css', '500.css'] },
  { pkg: 'noto-sans-tc', files: ['300.css', '400.css'] },
  { pkg: 'cormorant-garamond', files: ['300.css', '400.css', '400-italic.css'] },
];

function findPkg(name) {
  for (const d of fs.readdirSync(src)) {
    const p = path.join(src, d, 'package');
    if (d.includes(name) && fs.existsSync(path.join(p, 'package.json'))) return p;
    const n = path.join(src, d);
    if (d === name && fs.existsSync(path.join(n, 'package.json'))) return n;
  }
  throw new Error('font package not found: ' + name);
}

// characters used anywhere on the site
const used = new Set();
for (let c = 0x20; c < 0x7f; c++) used.add(c);
for (const f of fs.readdirSync(root)) {
  if (!/\.(html)$/.test(f)) continue;
  for (const ch of fs.readFileSync(path.join(root, f), 'utf8')) used.add(ch.codePointAt(0));
}
for (const f of fs.readdirSync(path.join(root, 'assets'))) {
  if (!/\.js$/.test(f)) continue;
  for (const ch of fs.readFileSync(path.join(root, 'assets', f), 'utf8')) used.add(ch.codePointAt(0));
}

function covers(range) {
  for (const part of range.split(',')) {
    const m = part.trim().replace(/^U\+/i, '').split('-');
    const a = parseInt(m[0], 16), b = m[1] ? parseInt(m[1], 16) : a;
    for (const cp of used) if (cp >= a && cp <= b) return true;
  }
  return false;
}

const outDir = path.join(root, 'assets', 'fonts');
for (const f of fs.readdirSync(outDir)) fs.unlinkSync(path.join(outDir, f));
let css = '/* generated by tools/build-fonts.mjs — do not edit */\n';
let count = 0, bytes = 0;
for (const face of FACES) {
  const dir = findPkg(face.pkg);
  for (const file of face.files) {
    const text = fs.readFileSync(path.join(dir, file), 'utf8');
    for (const block of text.match(/@font-face\s*{[^}]*}/g) || []) {
      const range = (block.match(/unicode-range:\s*([^;]+);/) || [])[1];
      if (range && !covers(range)) continue;
      const woff2 = block.match(/url\(\.\/files\/([^)]+\.woff2)\)/)[1];
      fs.copyFileSync(path.join(dir, 'files', woff2), path.join(outDir, woff2));
      bytes += fs.statSync(path.join(outDir, woff2)).size; count++;
      css += block
        .replace(/src:[^;]+;/, `src: url(./fonts/${woff2}) format('woff2');`) + '\n';
    }
  }
}
fs.writeFileSync(path.join(root, 'assets', 'fonts.css'), css);
console.log(`fonts: ${count} files, ${(bytes / 1024).toFixed(0)} KB`);
